# Generated by Django 4.0.6 on 2022-07-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='number_of_user',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
